apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-test
  name: nginx-test
  namespace: default
spec:
  containers:
  - image: naginx
    name: nginx-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
